### Numpy indexing and selection
->  Indexing is going to allow us to grab a single element from either a one dimensional array or two dimensional array

-> Selection will allow us to grab a slice or a chunk of Elements from a one dimensional or two dimensional array

In [7]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### One dimensional array

In [8]:
# Bracket Indexing and selection of one dimensional array
arr[8]

8

In [9]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[:5]

array([0, 1, 2, 3, 4])

In [12]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
# Brodcast functions and operations

arr + 100


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [14]:
new_arr = arr/2

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [20]:
slice_of_arr[:] = 99
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
# If you not want to change a original array then make a copy of origignal array
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy[:] = 1000
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Two Dimenson array

In [26]:
# Indexing
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d 

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d.shape

(3, 3)

In [32]:
arr_2d[2][2]

45

In [33]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [34]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

### Conditional Selection
Conditional Selection is a fundamental concept that directly translates the pandaas and it allows you to use comparison operators to actually grab elements 

In [37]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
bool_Arr = arr > 4
bool_Arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [39]:
arr[bool_Arr]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
arr[arr < 6]

array([0, 1, 2, 3, 4, 5])