In [1]:
import numpy as np

### Creating numpy array from list

In [2]:
mylist = [1,2,3]
type(mylist)

list

In [6]:
arr = np.array(mylist)
type(arr)

numpy.ndarray

In [7]:
# Nested List
mylist = [[1,2,3],[4,5,6],[7,8,9]]
mymatrix = np.array(mylist)
type(mymatrix)

numpy.ndarray

In [8]:
### Atrributes
mymatrix.shape

(3, 3)

In [10]:
# Builtin Methods
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
# Tuple
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [20]:
# linear space array
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [22]:
#Daigonal Matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
# Random numbers
np.random.rand(5,5)

array([[0.42570943, 0.54412447, 0.77089358, 0.51218   , 0.08245294],
       [0.12007497, 0.52221327, 0.62583812, 0.78686715, 0.15353704],
       [0.84019295, 0.74214899, 0.58545395, 0.81009211, 0.36234989],
       [0.59156872, 0.1363492 , 0.36912975, 0.95955526, 0.29214047],
       [0.99752342, 0.70586626, 0.44189323, 0.72352537, 0.76700776]])

In [27]:
# Returns a Standard Normal Distribution
# Standard Normal Distribution has a mean Zero and a Standard deviation of one
np.random.randn(4)

array([ 0.05772985,  0.1770747 , -0.1866242 , -0.18242175])

In [ ]:
# Specify your mean and deviation

In [29]:
np.random.randint(1,100,10)

array([ 8, 17, 42, 56, 90, 78, 69, 53, 63, 46])

In [32]:
# Each time you get a different numbers therfore we have to set a seed to produce same reuslt
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [33]:
# Array attributes and Methods
arr = np.arange(25)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
ranarr = np.random.randint(0,50,10)
ranarr

array([41, 48, 32, 20, 22, 22, 10, 21, 27, 28])

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
ranarr.max()

48

In [38]:
ranarr.min()

10

In [40]:
ranarr.argmax() # Location of Maximum Element

1

In [41]:
ranarr.argmin() # Location of Minimum Element

6

In [42]:
ranarr.dtype # data type of array

dtype('int64')

In [44]:
arr.dtype

dtype('int64')